In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3], np.int16)

In [3]:
print(x)

print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
x

print(x[0]); print(x[1]); print(x[2])

1
2
3


In [5]:
x

array([1, 2, 3], dtype=int16)

In [6]:
print(x[-1])

3


In [7]:
print(x[3])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int16)

print(x)

[[1 2 3]
 [4 5 6]]


In [10]:
print(x[:, 0])

[1 4]


In [11]:
print(x[:, 1])

[2 5]


In [12]:
print(x[:, 2])

[3 6]


In [14]:
print(x[0, :])

[1 2 3]


In [20]:
x = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)

print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [21]:
print(x[0, 0, 0])

1


In [22]:
print(x[0, 0, 2])

3


In [23]:
y = np.array([1, 2, 3])

In [25]:
y[0]

1

In [26]:
y[2]

3

In [28]:
print(x[1, 0, 2])

-2


In [29]:
print(x[1, 1, 2])

-5


In [30]:
print(x[:, :, 0])

[[ 1  4]
 [ 0 -3]]


In [31]:
print(x[:, :, 1])

[[ 2  5]
 [-1 -4]]


In [32]:
print(x[:, 1, 1])

[ 5 -4]


In [33]:
print(x[1, 1, 2])

-5


In [34]:
print(x[0, 0, 0])

1


# Numpy Ndarrays Properties

In [35]:
x = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)

print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [41]:
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.size)
print(x.nbytes)

(2, 2, 3)
3
int16
12
24


In [42]:
print(x.T)

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]


# Numpy Constants

In [44]:
print(np.inf)
print(np.NAN)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)

print(np.e)
print(np.euler_gamma)
print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793
