In [1]:
import numpy as np

In [2]:
x = np.random.randint( low=0, high=9, size=10)
print(x)

[1 6 6 5 7 2 3 3 2 2]


In [3]:
x = np.random.rand(3, 3)
print(x)

[[ 0.62734104  0.19686662  0.20493573]
 [ 0.00432309  0.5818361   0.08351909]
 [ 0.97535607  0.17119634  0.85718257]]


In [4]:
x = np.random.rand(3, 3, 3)
print(x)

[[[ 0.76794279  0.15633282  0.47520536]
  [ 0.13328981  0.19718891  0.97586944]
  [ 0.8412306   0.96828094  0.5741657 ]]

 [[ 0.41294752  0.61829357  0.66721228]
  [ 0.45920338  0.7472284   0.42099913]
  [ 0.01972766  0.40906302  0.09605649]]

 [[ 0.36995563  0.72361119  0.69764776]
  [ 0.1109215   0.36126957  0.91994188]
  [ 0.85732784  0.26339348  0.82096469]]]


In [5]:
x = np.random.rand(2, 2, 2)
print(x)

[[[ 0.3884877   0.6838992 ]
  [ 0.38250086  0.29032266]]

 [[ 0.97748023  0.15199089]
  [ 0.77462267  0.14595816]]]
