In [1]:
import numpy as np

# Dot Product

In [2]:
print(np.dot(10, 5))

50


In [3]:
a = np.array([2, 4], np.uint8)
b = np.array([5, 6], np.uint8)

print(np.dot(a, b))

34


#### In Matrices multiplications, number of column of first matrix must match with number of rows of second matrix

In [5]:
a = np.array([[2, 4], [5, 8]], np.uint8)
b = np.array([[5, 6], [9, 3]], np.uint8)

print(np.dot(a, b))

[[46 24]
 [97 54]]


#### linalg stands for Linear Algebra. So, it is multi_dot product

In [8]:
a = np.random.rand(10, 5)
b = np.random.rand(5, 2)
c = np.random.rand(2, 3)
d = np.random.rand(3, 4)

e = np.linalg.multi_dot([a, b, c ,d])
print(e)

[[ 1.02161281  2.07297705  1.5417411   1.84791818]
 [ 0.96858729  1.97969355  1.5271633   1.76539445]
 [ 1.21514568  2.46715186  1.84054201  2.1993633 ]
 [ 0.84215572  1.71725935  1.30943277  1.53119206]
 [ 0.87549322  1.78607728  1.36510279  1.59259034]
 [ 1.44852138  2.95379177  2.25260234  2.63374801]
 [ 0.90579209  1.83104998  1.33534305  1.63195129]
 [ 1.22356362  2.48170352  1.84167959  2.2122234 ]
 [ 1.05063812  2.13892091  1.61777261  1.90701396]
 [ 1.80118908  3.65992157  2.74149035  3.26279618]]


# Vector Dot Product

In [9]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.vdot(a, b))

11


In [11]:
a = np.array([1 + 5j, 2 + 3j])
b = np.array([3 + 2j, 4 + 7j])

print(np.vdot(a, b))

(42-11j)


In [13]:
print(np.vdot(b, a))

(42+11j)


# Inner Product

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, 1, 0, 1, 0, 1])

print(np.inner(a, b))

12


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 1, 0], [1, 0, 1]])

print(np.inner(a, b))

[[ 2  4]
 [ 5 10]]


# QR Decomposition

In [16]:
a = np.random.rand(3, 3)
print(a)

[[ 0.06096886  0.35771268  0.94729211]
 [ 0.57340598  0.90108394  0.92015713]
 [ 0.40029059  0.46415691  0.61758131]]


In [17]:
q, r = np.linalg.qr(a)
print('q= ', q, '\n\nr = ', r, '\n')

print(np.dot(q, r))

q=  [[-0.0868555   0.890194    0.44722563]
 [-0.81686722  0.19332974 -0.54346256]
 [-0.57024912 -0.41252667  0.71037855]] 

r =  [[-0.70195739 -1.03182032 -1.18609893]
 [ 0.          0.3011629   0.76639873]
 [ 0.          0.          0.36229887]] 

[[ 0.06096886  0.35771268  0.94729211]
 [ 0.57340598  0.90108394  0.92015713]
 [ 0.40029059  0.46415691  0.61758131]]


# Determinent and Solving Linear Equations

#### Determinent

In [18]:
a = np.array([[5, 6], [3, 4]])

print(np.linalg.det(a))

2.0


In [21]:
a = np.array([[2, 1, -3], [4, -2, 1], [3, 5, -2]], np.int16)

b = np.array([-4, 9, 5], np.int16)

# ax =b

x = np.linalg.solve(a, b)
print(x)

[ 2.  1.  3.]
