# Array Manipulation Routines

In [2]:
import numpy as np

In [3]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [4]:
y = x.reshape((3, 2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [5]:
x = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [6]:
y = np.reshape(x, 6)
print(y)

[0 1 2 3 4 5]


In [7]:
print(x)

[[0 1 2]
 [3 4 5]]


#### NP Rav

In [8]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [9]:
print(x)

[[0 1 2]
 [3 4 5]]


#### NP Flaten for Image Processing

In [10]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


#### Row wise of X

In [11]:
y = x.flatten( 'C' )
print(y)

[0 1 2 3 4 5]


#### Column wise of X

In [12]:
y = x.flatten( 'F' )
print(y)

[0 3 1 4 2 5]


In [13]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)

print(x.dtype)

print(x)
print(y)


uint8
[1 2 3]
[4 5 6]


In [15]:
z = np.stack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [16]:
z = np.stack((x, y), axis = 0)
print(z)

[[1 2 3]
 [4 5 6]]


In [19]:
z = np.stack((x, y), axis = 1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
print(x)
print(y)

[1 2 3]
[4 5 6]


#### Depth Stack

In [21]:
z = np.dstack((x, y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


#### Z Shape

In [22]:
print(z.shape)

(1, 3, 2)


#### Horizontal Stack

In [23]:
z = np.hstack((x, y))
print(z)

[1 2 3 4 5 6]


#### Vertical Stack

In [24]:
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [25]:
print(z.shape)

(2, 3)


In [26]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


#### Split

In [27]:
a, b, c = np.split(x, 3)
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [28]:
x = np.random.rand(4, 4, 4)
print(x)

[[[ 0.79249934  0.88094985  0.8500134   0.6283162 ]
  [ 0.09342109  0.96258528  0.11490433  0.77161706]
  [ 0.19003871  0.23703101  0.51867684  0.79029596]
  [ 0.11426861  0.63875954  0.51243615  0.16715621]]

 [[ 0.03316508  0.18057899  0.90554827  0.99118914]
  [ 0.98154356  0.55942326  0.47072766  0.56069211]
  [ 0.60382525  0.51208213  0.36895001  0.89035686]
  [ 0.62407394  0.23511017  0.14999916  0.84019364]]

 [[ 0.27220055  0.69567493  0.90632682  0.88644752]
  [ 0.67131156  0.90551741  0.32741439  0.7411959 ]
  [ 0.44996498  0.69351787  0.67366943  0.48780896]
  [ 0.31045669  0.9935703   0.68678995  0.948608  ]]

 [[ 0.53864889  0.42224283  0.04557687  0.36057728]
  [ 0.02262667  0.61314263  0.89269828  0.58914805]
  [ 0.16971711  0.80440382  0.98989538  0.65351208]
  [ 0.58026222  0.53185372  0.73500249  0.58254684]]]


In [29]:
y, z = np.split(x, 2)
print(y, z)


[[[ 0.79249934  0.88094985  0.8500134   0.6283162 ]
  [ 0.09342109  0.96258528  0.11490433  0.77161706]
  [ 0.19003871  0.23703101  0.51867684  0.79029596]
  [ 0.11426861  0.63875954  0.51243615  0.16715621]]

 [[ 0.03316508  0.18057899  0.90554827  0.99118914]
  [ 0.98154356  0.55942326  0.47072766  0.56069211]
  [ 0.60382525  0.51208213  0.36895001  0.89035686]
  [ 0.62407394  0.23511017  0.14999916  0.84019364]]] [[[ 0.27220055  0.69567493  0.90632682  0.88644752]
  [ 0.67131156  0.90551741  0.32741439  0.7411959 ]
  [ 0.44996498  0.69351787  0.67366943  0.48780896]
  [ 0.31045669  0.9935703   0.68678995  0.948608  ]]

 [[ 0.53864889  0.42224283  0.04557687  0.36057728]
  [ 0.02262667  0.61314263  0.89269828  0.58914805]
  [ 0.16971711  0.80440382  0.98989538  0.65351208]
  [ 0.58026222  0.53185372  0.73500249  0.58254684]]]


#### Depth Split

In [30]:
y, z = np.dsplit(x, 2)
print(y, z)


[[[ 0.79249934  0.88094985]
  [ 0.09342109  0.96258528]
  [ 0.19003871  0.23703101]
  [ 0.11426861  0.63875954]]

 [[ 0.03316508  0.18057899]
  [ 0.98154356  0.55942326]
  [ 0.60382525  0.51208213]
  [ 0.62407394  0.23511017]]

 [[ 0.27220055  0.69567493]
  [ 0.67131156  0.90551741]
  [ 0.44996498  0.69351787]
  [ 0.31045669  0.9935703 ]]

 [[ 0.53864889  0.42224283]
  [ 0.02262667  0.61314263]
  [ 0.16971711  0.80440382]
  [ 0.58026222  0.53185372]]] [[[ 0.8500134   0.6283162 ]
  [ 0.11490433  0.77161706]
  [ 0.51867684  0.79029596]
  [ 0.51243615  0.16715621]]

 [[ 0.90554827  0.99118914]
  [ 0.47072766  0.56069211]
  [ 0.36895001  0.89035686]
  [ 0.14999916  0.84019364]]

 [[ 0.90632682  0.88644752]
  [ 0.32741439  0.7411959 ]
  [ 0.67366943  0.48780896]
  [ 0.68678995  0.948608  ]]

 [[ 0.04557687  0.36057728]
  [ 0.89269828  0.58914805]
  [ 0.98989538  0.65351208]
  [ 0.73500249  0.58254684]]]


#### Height or Horizontal Split

In [31]:
y, z = np.hsplit(x, 2)
print(y, z)

[[[ 0.79249934  0.88094985  0.8500134   0.6283162 ]
  [ 0.09342109  0.96258528  0.11490433  0.77161706]]

 [[ 0.03316508  0.18057899  0.90554827  0.99118914]
  [ 0.98154356  0.55942326  0.47072766  0.56069211]]

 [[ 0.27220055  0.69567493  0.90632682  0.88644752]
  [ 0.67131156  0.90551741  0.32741439  0.7411959 ]]

 [[ 0.53864889  0.42224283  0.04557687  0.36057728]
  [ 0.02262667  0.61314263  0.89269828  0.58914805]]] [[[ 0.19003871  0.23703101  0.51867684  0.79029596]
  [ 0.11426861  0.63875954  0.51243615  0.16715621]]

 [[ 0.60382525  0.51208213  0.36895001  0.89035686]
  [ 0.62407394  0.23511017  0.14999916  0.84019364]]

 [[ 0.44996498  0.69351787  0.67366943  0.48780896]
  [ 0.31045669  0.9935703   0.68678995  0.948608  ]]

 [[ 0.16971711  0.80440382  0.98989538  0.65351208]
  [ 0.58026222  0.53185372  0.73500249  0.58254684]]]


#### Veritical Split

In [32]:
y, z = np.vsplit(x, 2)
print(y, z)

[[[ 0.79249934  0.88094985  0.8500134   0.6283162 ]
  [ 0.09342109  0.96258528  0.11490433  0.77161706]
  [ 0.19003871  0.23703101  0.51867684  0.79029596]
  [ 0.11426861  0.63875954  0.51243615  0.16715621]]

 [[ 0.03316508  0.18057899  0.90554827  0.99118914]
  [ 0.98154356  0.55942326  0.47072766  0.56069211]
  [ 0.60382525  0.51208213  0.36895001  0.89035686]
  [ 0.62407394  0.23511017  0.14999916  0.84019364]]] [[[ 0.27220055  0.69567493  0.90632682  0.88644752]
  [ 0.67131156  0.90551741  0.32741439  0.7411959 ]
  [ 0.44996498  0.69351787  0.67366943  0.48780896]
  [ 0.31045669  0.9935703   0.68678995  0.948608  ]]

 [[ 0.53864889  0.42224283  0.04557687  0.36057728]
  [ 0.02262667  0.61314263  0.89269828  0.58914805]
  [ 0.16971711  0.80440382  0.98989538  0.65351208]
  [ 0.58026222  0.53185372  0.73500249  0.58254684]]]


In [33]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### Array Flip

In [34]:
y = np.flip(x, axis=-1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [35]:
y = np.flip(x, axis= 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [36]:
y = np.flip(x, axis=1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


#### Array Flip left to right

In [38]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


#### Array Flip Up Down

In [40]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


#### Array Roll

#### First 8 elment shifted to last 8. While, last 8 shifted to first 8 elements. This is Roll

In [41]:
y = np.roll(x, 8)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


#### Array Rotation

#### Rotating Array 90 Degrees Anti Clockwise

In [42]:
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
